//errors
export const GET_ERRORS = 'GET_ERRORS'
//auth
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const INFO_SUBMITTING = 'INFO_SUBMITTING'
export const INFO_SUBMITTED = 'INFO_SUBMITTED'
export const ON_LOGIN_INPUT_CHANGE = 'ON_LOGIN_INPUT_CHANGE'
export const ON_REGISTER_INPUT_CHANGE = 'ON_REGISTER_INPUT_CHANGE'
export const GET_CURRENT_AUTH_STATE = 'GET_CURRENT_AUTH_STATE'
export const CLEAR_REGISTER_INPUT = 'CLEAR_REGISTER_INPUT'
export const CLEAR_LOGIN_INPUT = 'CLEAR_LOGIN_INPUT'

//paper
export const GET_PAPER = 'GET_PAPER'
export const GET_PAPERS_ALL = 'GET_PAPERS_ALL'
export const PAPERS_LOADING = 'PAPERS_LOADING'
export const PAPER_NOT_FOUND = 'PAPER_NOT_FOUND'
export const CLEAR_CURRENT_PAPER = 'CLEAR_CURRENT_PAPER'
export const GET_CURRENT_USER_PAPERS = 'GET_CURRENT_USER_PAPERS'
export const DELETE_PAPERS = 'DELETE_PAPERS'
//spinner
export const LOADING = 'LOADING'
export const SUBMITTING = 'SUBMITTING'
export const LOADED = 'LOADED'
export const SUBMITTED = 'SUBMITTED'
